### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by blqq305** [echosoar/medit#11]
上传成功后一直这样，我是不是哪里弄错了。
[图片](https://raw.githubusercontent.com/blqq305/Learn/master/QQ%E5%9B%BE%E7%89%8720171124170635.png)

[图片2](https://raw.githubusercontent.com/blqq305/Learn/master/QQ%E5%9B%BE%E7%89%8720171124170741.png)

**Comment by Sun-Target** [comment]
你好，有解决的办法吗？我也遇到这个问题了 @blqq305

**Comment by echosoar** [comment]
Duplicate of #9
