### ISSUE TITLE
图片上传的问题？

### ISSUE THREAD

**Issue by Sun-Target** [echosoar/medit#12]
图片上传成功后，返回了数据，但是没有进入success和error区间，请问这个是什么问题呢
![image](https://user-images.githubusercontent.com/19965020/33300412-1fe3e8da-d42b-11e7-8dec-b51a1fb3c322.png)

**Comment by echosoar** [comment]
{ "code": "success", "data": { "width": "990", "height": "1080", "url": "//xxx.xxx.xxx/xxx.png", ... } }
服务器返回的内容里面code为success应该就可以了
