### ISSUE TITLE
上传图片不成功 报错：image type limit jpg,jpeg,png,gif

### ISSUE THREAD

**Issue by max-level** [echosoar/medit#2]
图片检查没问题，就是报这个类型的错

**Comment by echosoar** [comment]
publish/2.0.0
可以把ext设置为false，就不会进行type校验了
meditObject.image({ path: 'https://sm.ms/api/upload', size: 102400000, ext: false, success:function(res){ console.log(res); }, error:function(msg){ alert("error : " + msg); }, params: { id: '123455', name: 'echosoar' } });
