### ISSUE TITLE
上传图片能传参数吗？

### ISSUE THREAD

**Issue by max-level** [echosoar/medit#3]
上传图片能传参数吗？比如：
`{
    params: {
         apptoken: 'sdfdfsfsd'
    }
}`

**Comment by echosoar** [comment]
暂时带参数可以使用GET方式挂在上传路径后面
`meditObj.image({
path:'https://sm.ms/api/upload?apptoken=sdfdfdfsd'
})`
这个问题马上会修复

**Comment by echosoar** [comment]
已经fixed了
publish/2.0.0
`
meditObject.image({
	path: 'https://sm.ms/api/upload',
	size: 102400000,
	ext: false,
	success:function(res){
		console.log(res);
	},
	error:function(msg){
		alert("error : " + msg);
	},
	params: {
		id: '123455',
		name: 'echosoar'
	}
});
`
