### ISSUE TITLE
vue、react、angularjs等框架中如何使用？

### ISSUE THREAD

**Issue by AZmake** [echosoar/medit#5]
**以下仅仅是使用体验，纯属个人意见**

1、没有AMD、CMD、ES6的加载模式的判断
2、没有npm包
3、那个demo的index文件能不能弄个完整的html？不完整会乱码的。
4、meditToolImage 图片问题，好像这些按钮是动态插入span实现的，那么是否能在CSS里面写死？那样就不会有额外的图片，所有图片都编程base64？
5、我改了一下源码的demo的index.html为标准的index.html和medit.min.js的路径，demo跑起来了，看到粉色光标，但是在手机上唤不起输入法？
6、可以在github.io来个正常的demo？非gif图的

我简单的改了一下，在vue里面使用没有成功

**`源码1446行`**
```js
clearInterval(this.autoSaveInterval);
let _this = this;
this.autoSaveInterval = setInterval(function(){
	let nowData = _this.getContent(true);
	localStorage.setItem("meditAutosave"+appId,nowData);
	callBack(nowData, (new Date())-0);
},1000);
```
会导致下面的autoSaveInfo元素找不到的时候，控制台就不停的打印`Uncaught TypeError: Cannot set property 'innerHTML' of null`，页面卡死或者相应缓慢

```js
me.autoSave("edit", function(data, time){
     document.getElementById("autoSaveInfo").innerHTML = "Auto save at " + (new Date(time)).toString().replace(/\(.*\)/,"");
});
```

**使用localStorage作为自动保存，会不会爆掉？好像localStorage的存储不是很大**
**能不能监测到改动停止1s左右才保存？**

**Comment by echosoar** [comment]
非常感谢提出这个issue
后期会根据你提出意见进行功能和使用方面的修改
所有的修改进度都会在这个issue中进行回复

=============

【4】之所以没有在css中把图标写死，是因为插件的图标icon也需要有一种接入的方式，比如https://github.com/EchoFed/medit-plugin-blockquote
【6】在 https://medit.js.org 里面点击gif图是有在线demo的

**Comment by AZmake** [comment]
@echosoar `谢谢楼主，我仔细看看`
