### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by blqq305** [echosoar/medit#9]
您好，图片上传后没有回调success或者error方法，图片上传成功了窗口没有关闭，也没有显示图片。请问图片上传成功后服务器返回的格式如何定义？

**Comment by echosoar** [comment]
https://github.com/echosoar/medit/blob/1c6df2ddc3dad8b825aa89b87a268ecc2fa2a1a5/demo/index.html#L84~L98

是有success和error方法的~

**Comment by echosoar** [comment]
服务器返回的格式：
`
{
    "data": {
        "width": "990",
        "height": "1080",
        "url": "//xxx.xxx.xxx/xxx.png",
        ...
    }
}
`

**Comment by blqq305** [comment]
@echosoar 我再试下哈，方法我见到有，只是我上传成功了图片，但是没有执行success方法

**Comment by Sun-Target** [comment]
我也遇到这种问题，明明已经写到服务器了，就是没有进入这两个区间，有解决的了吗？

**Comment by echosoar** [comment]
服务器返回的json中添加一个code=success
{ "code": "success", "data": { "width": "990", "height": "1080", "url": "//xxx.xxx.xxx/xxx.png", ... } }

**Comment by Sun-Target** [comment]
非常感谢!真的可以了！ @echosoar
